-- Insertions dans la Table Utilisateurs
INSERT INTO utilisateurs (nom, email, mot_de_passe, type)
VALUES
    ("Alice Dupont", "alice@example.com", "password123", "Utilisateur"),
    ("Bob Martin", "bob@example.com", "password123", "Botaniste"),
    ("Claire Dupuis", "claire@example.com", "password456", "Utilisateur"),
    ("David Tremblay", "david@example.com", "password789", "Botaniste"),
    ("Élise Lavoie", "elise@example.com", "passwordabc", "Utilisateur"),
    ("François Leclerc", "francois@example.com", "passworddef", "Botaniste"),
    ("Gabrielle Gagnon", "gabrielle@example.com", "passwordghi", "Utilisateur"),
    ("Hugo Bélanger", "hugo@example.com", "passwordjkl", "Botaniste"),
    ("Isabelle Fortin", "isabelle@example.com", "passwordmno", "Utilisateur"),
    ("Jean-Pierre Bergeron", "jeanpierre@example.com", "passwordpqr", "Botaniste"),
    ("Julie Martin", "julie@example.com", "passwordstu", "Utilisateur"),
    ("Kevin Tremblay", "kevin@example.com", "passwordvwx", "Botaniste"),
    ("Léa Gagnon", "lea@example.com", "passwordyz", "Utilisateur"),
    ("Martin Bélanger", "martin@example.com", "password123", "Botaniste"),
    ("Nathalie Fortin", "nathalie@example.com", "password456", "Utilisateur"),
    ("Olivier Bergeron", "olivier@example.com", "password789", "Botaniste"),
    ("Patricia Dupont", "patricia@example.com", "passwordabc", "Utilisateur"),
    ("Quentin Lavoie", "quentin@example.com", "passworddef", "Botaniste"),
    ("Rachel Gagnon", "rachel@example.com", "passwordghi", "Utilisateur"),
    ("Sébastien Martin", "sebastien@example.com", "passwordjkl", "Botaniste"),
    ("Sophie Tremblay", "sophie@example.com", "passwordmno", "Utilisateur"),
    ("Thierry Bélanger", "thierry@example.com", "passwordpqr", "Botaniste"),
    ("Valérie Fortin", "valerie@example.com", "passwordstu", "Utilisateur"),
    ("William Bergeron", "william@example.com", "passwordvwx", "Botaniste"),
    ("Xavier Dupont", "xavier@example.com", "passwordyz", "Utilisateur"),
    ("Yasmine Lavoie", "yasmine@example.com", "password123", "Botaniste"),
    ("Zoé Gagnon", "zoe@example.com", "password456", "Utilisateur"),
    ("Albert Martin", "albert@example.com", "password789", "Botaniste"),
    ("Béatrice Tremblay", "beatrice@example.com", "passwordabc", "Utilisateur"),
    ("Cédric Bélanger", "cedric@example.com", "passworddef", "Botaniste"),
    ("Diane Fortin", "diane@example.com", "passwordghi", "Utilisateur"),
    ("Éric Dupont", "eric@example.com", "passwordjkl", "Botaniste"),
    ("Fanny Gagnon", "fanny@example.com", "passwordmno", "Utilisateur"),
    ("Gilles Martin", "gilles@example.com", "passwordpqr", "Botaniste"),
    ("Hélène Tremblay", "helene@example.com", "passwordstu", "Utilisateur"),
    ("Isaac Lavoie", "isaac@example.com", "passwordvwx", "Botaniste"),
    ("Jennifer Bergeron", "jennifer@example.com", "passwordyz", "Utilisateur"),
    ("Karl Fortin", "karl@example.com", "password123", "Botaniste"),
    ("Linda Dupont", "linda@example.com", "password456", "Utilisateur"),
    ("Mathieu Gagnon", "mathieu@example.com", "password789", "Botaniste"),
    ("Nancy Martin", "nancy@example.com", "passwordabc", "Utilisateur"),
    ("Olivier Tremblay", "olivier2@example.com", "passworddef", "Botaniste"),
    ("Patricia Dupuis", "patricia2@example.com", "passwordghi", "Utilisateur"),
    ("Quentin Lefebvre", "quentin2@example.com", "passwordjkl", "Botaniste"),
    ("Rachel Gauthier", "rachel2@example.com", "passwordmno", "Utilisateur"),
    ("Sébastien Dubois", "sebastien2@example.com", "passwordpqr", "Botaniste"),
    ("Sophie Lefebvre", "sophie2@example.com", "passwordstu", "Utilisateur"),
    ("Thierry Gosselin", "thierry2@example.com", "passwordvwx", "Botaniste"),
    ("Valérie Rousseau", "valerie2@example.com", "passwordyz", "Utilisateur");

-- Insertions dans la Table Botanistes
INSERT INTO botanistes (id_utilisateur, specialisation, annees_experience)
VALUES
    (2, "Botanique tropicale", 5),
    (4, "Botanique des déserts", 7),
    (6, "Botanique marine", 3),
    (8, "Botanique des montagnes", 10),
    (10, "Botanique des prairies", 2),
    (12, "Botanique forestière", 8),
    (14, "Botanique côtière", 4),
    (16, "Botanique médicinale", 6),
    (18, "Botanique alimentaire", 9),
    (20, "Botanique ornementale", 5),
    (22, "Botanique aquatique", 7),
    (24, "Botanique exotique", 3),
    (26, "Botanique florale", 11),
    (28, "Botanique aromatique", 6),
    (30, "Botanique subtropicale", 8),
    (32, "Botanique sauvage", 5),
    (34, "Botanique méditerranéenne", 9),
    (36, "Botanique alpine", 4),
    (38, "Botanique désertique", 7),
    (40, "Botanique polaire", 3),
    (42, "Botanique volcanique", 6),
    (44, "Botanique lacustre", 5),
    (46, "Botanique abyssale", 8),
    (48, "Botanique cavernicole", 4),
    (50, "Botanique lunaire", 2);

-- Insertions dans la Table Plantes
INSERT INTO plantes (nom, type, instructions_soin, id_utilisateur)
VALUES
    ("Ficus", "Plante d’intérieur", "Arroser une fois par semaine", 1),
    ("Orchidée", "Fleur", "Exposer à la lumière indirecte", 1),
    ("Cactus", "Plante désertique", "Arroser rarement", 4),
    ("Algue", "Plante aquatique", "Maintenir dans un aquarium", 6),
    ("Épinette", "Arbre", "Planter en plein soleil", 8),
    ("Rose", "Fleur", "Tailler les roses fanées", 10),
    ("Tomate", "Légume", "Arroser régulièrement", 12),
    ("Bambou", "Plante d’intérieur", "Arroser abondamment", 14),
    ("Tulipe", "Fleur", "Planter en automne", 16),
    ("Sauge", "Herbe aromatique", "Récolter les feuilles pour la cuisine", 18),
    ("Lavande", "Fleur", "Exposer au soleil", 20),
    ("Chêne", "Arbre", "Planter en automne", 22),
    ("Pomme de terre", "Légume", "Butter les plants", 24),
    ("Lys", "Fleur", "Arroser régulièrement", 26),
    ("Menthe", "Herbe aromatique", "Envahit rapidement, planter en pot", 28),
    ("Érable", "Arbre", "Élaguer les branches mortes", 30),
    ("Carotte", "Légume", "Arroser régulièrement", 32),
    ("Origan", "Herbe aromatique", "Utiliser en cuisine", 34),
    ("Baobab", "Arbre", "Croissance lente", 36),
    ("Laitue", "Légume", "Arroser régulièrement", 38),
    ("Thym", "Herbe aromatique", "Utiliser en cuisine", 40),
    ("Palmier", "Arbre", "Arroser modérément", 42),
    ("Courgette", "Légume", "Arroser abondamment", 44),
    ("Basilic", "Herbe aromatique", "Utiliser en cuisine", 46),
    ("Cerisier", "Arbre", "Taille en hiver", 48),
    ("Concombre", "Légume", "Tuteurer les plants", 50);

-- Insertions dans la Table Conseils
INSERT INTO conseils (contenu, id_botaniste, id_plante)
VALUES
    ("Utilisez un terreau pour orchidées pour un meilleur drainage", 2, 2),
    ("Évitez de trop arroser les cactus pour éviter la pourriture des racines", 4, 3),
    ("Nettoyez régulièrement les algues de l'aquarium", 6, 4),
    ("Taillez les branches mortes de l'épinette", 8, 5),
    ("Supprimez les feuilles malades des roses", 10, 6),
    ("Buttez les plants de tomates pour les protéger", 12, 7),
    ("Fertilisez le bambou au printemps", 14, 8),
    ("Plantez les bulbes de tulipes à 15 cm de profondeur", 16, 9),
    ("Récoltez les feuilles de sauge en été", 18, 10),
    ("Taillez la lavande après la floraison", 20, 11),
    ("Élaguez l'érable en fin d'hiver", 22, 12),
    ("Buttez les plants de pommes de terre en cours de croissance", 24, 13),
    ("Taillez les lys après la floraison", 26, 14),
    ("Taillez la menthe pour éviter qu'elle envahisse", 28, 15),
    ("Élaguez le palmier au printemps", 30, 16),
    ("Arrosez les laitues régulièrement pour éviter l'amertume", 32, 17),
    ("Utilisez du thym frais en cuisine", 34, 18),
    ("Le baobab nécessite peu d'eau", 36, 19),
    ("Arrosez les plants de courgettes abondamment", 38, 20),
    ("Le basilic parfume les plats", 40, 21),
    ("Taillez le cerisier pour favoriser la fructification", 42, 22),
    ("Tuteurez les plants de concombre pour les soutenir", 44, 23);


-- Insertions dans la Table Sessions de Garde
INSERT INTO sessions_garde (id_plante, id_gardien, date_debut, date_fin, commentaires)
VALUES
    (1, 2, "2024-01-01", "2024-01-07", "Plante bien entretenue"),
    (2, 4, "2024-02-15", "2024-02-21", "Orchidée en floraison"),
    (3, 6, "2024-03-10", "2024-03-17", "Cactus en croissance"),
    (4, 8, "2024-04-20", "2024-04-27", "Algues en expansion"),
    (5, 10, "2024-05-05", "2024-05-12", "Épinette en bonne santé"),
    (6, 12, "2024-06-15", "2024-06-22", "Roses en boutons"),
    (7, 14, "2024-07-01", "2024-07-07", "Tomates en croissance");